name: Deploy to AWS EC2

on:
  push:
    branches: [ main ] # Tự động chạy khi bạn push vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/bff-nodejs-ts
            git pull origin main
            npm install
            npm run build
            pm2 restart my-bff || pm2 start dist/index.js --name "my-bff"
